version: '3.8'
services:
  courses:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/uecemy_courses
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
